# Generated by Django 4.2 on 2023-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Раздел 1', 'Раздел 1'), ('Раздел 2', 'Раздел 2')], max_length=50, null=True),
        ),
    ]
